---
- name: Deploy image and stylesheet
  hosts: web
  become: yes
  tasks:
    - name: install_docker_compose
      include_role:
        name: install_docker_compose

    - name: restart_web_compose
      include_role:
        name: restart_web_compose