version: "2"
services:
  tomcat:
    restart: always
    image: 192.168.242.91:5000/tomcat:{{docker_image_version}}
    container_name: tomcat
    volumes:
      - "{{dynamic_data_path}}:/usr/local/tomcat/data"
    networks:
      - backend

  nginx:
    restart: always
    image: 192.168.242.91:5000/nginx:{{docker_image_version}}
    container_name: nginx
    networks:
      - frontend
      - backend
    ports:
      - "80:80"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 133.10.10.0/24
          gateway: 133.10.10.1